# Paperspace Gradient workflow
# Save this file as `workspace.yaml` at the root of your repo/project.
# If you're uploading files directly to a Gradient Project (not using Git),
# you can remove the `workspace.repo` block.
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/StephaChrGruber/price-prediction-workflow.git
  TrainPricePrediction:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      generatedPrices:
        type: dataset
        with:
          ref: dsdazko82wby9he
    env:
      MONGO_URI: "mongodb://admin:2059$tephan5203@94.130.171.244:27017/?authSource=admin&readPreference=secondaryPreferred&directConnection=true"
      MONGO_DB: PriceForecast
      COLL_STOCK: DailyStockData
      COLL_CRYPTO: DailyCryptoData
      COLL_FX: DailyCurrencyExchangeRates
      COLL_NEWS: NewsHeadlines
      COLL_WEATHER: DailyWeatherData
      COLL_PRED: PricePredictions

      # Modeling knobs
      LOOKBACK: "180"
      HORIZONS_TD: "5,21,126,252"     # 1m, 6m, 1y in trading days
      HORIZONS_CAL: "7,30,182,365"    # 1m, 6m, 1y in calendar days
      USE_TRADING_DAYS: "false"      # set to "false" to use calendar horizons

      # Quantiles (optional)
      USE_QUANTILES: "true"         # "true" → p50/p90; "false" → point estimates
      QUANTILES: "0.5,0.9"

      # Weather settings
      WEATHER_PCA: "12"
      WEATHER_AGG: "mean"           # mean | median
      FOLD_AWARE_WEATHER_PCA: "false"  # set "true" if using walk-forward and you want fold-aware PCA

      # Training config
      WALK_FORWARD: "false"
      TRAIN_SPAN_DAYS: "1095"       # 3 years
      VAL_SPAN_DAYS: "90"
      STEP_DAYS: "90"
      BATCH: "256"
      EPOCHS: "15"
      LR: "0.0007"
      DROPOUT: "0.15"
      LAYERS: "2"
      HIDDEN: "128"
      WEIGHT_DECAY: "0.0001"

      # Output
      TOP_K: "20"
      RANK_HORIZON: "1y"           # one of {1m,6m,1y}
      RANK_QUANTILE: "0.5"         # used when USE_QUANTILES=true
      ARTIFACTS_DIR: "outputs"
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        pip install --upgrade pip
        pip install -r requirements.txt
        python -X faulthandler training.py
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
#schedules:
  # Weekly retrain: Mondays 02:00 UTC
#  - cron: "0 2 * * 1"
#    job: train
